### ISSUE TITLE
data

### ISSUE THREAD

**Issue by 3300780** [julibinho/2dSS#6]
Bonjour madame,
Auriez vous des fichiers plus long a nous fournir s'il vous plait?
Cordialement,
Charlotte.

**Comment by julibinho** [comment]
Bonsoir,

Vous voulez dire des fichiers avec  plus de sequences, c'est ça?
Ou bien avec des sequences plus longues?

à+

**Comment by julibinho** [comment]
J'ai mis des nouveau fichiers dans le repertoire data Acof.2dpred and Acof.aln

à+

**Comment by 3300780** [comment]
les nouveaux fichiers ne fonctionnes pas avec vos scripts il manque un 2 quelque part donc je l' ai remis du coup le premier script fonctionne mais lorsque j'execute le deuxieme script il boucle indefiniment.
"cochard@cochard-X451MA:/var/www/html/2dSS-master/scripts$ python 2dss.py  -inputFile aln -outputFile res
^CTraceback (most recent call last):
  File "2dss.py", line 309, in <module>
    info = info + showAlig(data, it, x, yBase, yHigh, 3, start, end, True)
  File "2dss.py", line 264, in showAlig
    info += represent2DSS(x, yBase, yHigh, seqID, structure, aligSeq, start, end, firstSeq)
  File "2dss.py", line 96, in represent2DSS
    seq2DSSSVG = represent2DObjects(x + X_TEXT_CORRECTION, yBase, yHigh, structure);
  File "2dss.py", line 177, in represent2DObjects
    if (i < len(seq2DSS) and seq2DSS[i].upper() == "-"):
KeyboardInterrupt
"

**Comment by 3408247** [comment]
Bonjour Madame, 

Voici le problème dont nous vous parlons. (voir capture écran)
![screenshot from 2017-03-09 14-21-27](https://cloud.githubusercontent.com/assets/16761614/23751999/ea0a3f24-04d3-11e7-9ed7-8038d4f32257.png)
